notARepository: quit
gui:
  showBottomLine: false
  nerdFontsVersion: '3'
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6da95" # Green
      - bold
    inactiveBorderColor:
      - "#cad3f5" # Text
    optionsTextColor:
      - "#8aadf4" # Blue
    selectedLineBgColor:
      - "#363a4f" # Surface0
    selectedRangeBgColor:
      - "#363a4f" # Surface0
    cherryPickedCommitBgColor:
      - "#8bd5ca" # Teal
    cherryPickedCommitFgColor:
      - "#8aadf4" # Blue
    unstagedChangesColor:
      - red # Red
git:
  pagers:
    - pager: delta --paging=never --diff-so-fancy  --features="interactive catppuccin-macchiato"
os:
  editPreset: 'nvim-remote'
